with (clawr)
    instance_destroy()
with (clawl)
    instance_destroy()
with (fang)
    instance_destroy()
with (oAutoHordeXEyes)
    instance_destroy()
with (oAutoHordeXCamera)
    instance_destroy()
with (oCrystalSolidX)
    instance_destroy(oCrystalSolidX)
dsolid = 0
with (disolid1)
    instance_destroy()
with (disolid2)
    instance_destroy()
with (disolid3)
    instance_destroy()
with (disolid4)
    instance_destroy()
